[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/affirm-authorize"
  to = "/.netlify/functions/affirm-authorize"
  status = 200

[[redirects]]
  from = "/api/card-checkout"
  to = "/.netlify/functions/card-checkout"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
